--CREATE TABLE PLAYER (
--  id int AUTO_INCREMENT,
--  firstName varchar(50) NOT NULL,
--  lastName varchar(50) NOT NULL,
--  teamCity varchar(50) NOT NULL,
--  teamName varchar(50) NOT NULL,
--  position varchar(50) NOT NULL,
--  totalPoints DOUBLE NOT NULL
--  team_id, starting DOUBLE NOT NULL,
--  starting BIT
--);

INSERT INTO TEAM (team_city, team_name) VALUES ('test', 'team')

INSERT INTO OWNER (username, password, team_name) VALUES ('manager', 'pass', 'team')

-- Arlington Renegades
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kevin', 'Anderson', 'Arlington', 'Renegades', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Drew', 'Plitt', 'Arlington', 'Renegades', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kyle', 'Sloter', 'Arlington', 'Renegades', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jeremy', 'Cox', 'Arlington', 'Renegades', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kenneth', 'Farrow', 'Arlington', 'Renegades', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Keith', 'Ford', 'Arlington', 'Renegades', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('De’Veon', 'Smith', 'Arlington', 'Renegades', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('De’Montre', 'Tuggle', 'Arlington', 'Renegades', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jackson', 'Anthrop', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brandon', 'Arconado', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kameron', 'Brown', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Sean', 'Modster', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Flynn', 'Nagle', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jordan', 'Smallwood', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('JaCorey', 'Sullivan', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Tyler', 'Vaughns', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Quintin', 'Vinzant', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Chad', 'Williams', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Lujuan', 'Winningham', 'Arlington', 'Renegades', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Shaun', 'Beyer', 'Arlington', 'Renegades', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jibri', 'Blount', 'Arlington', 'Renegades', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Sal', 'Cannella', 'Arlington', 'Renegades', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Alex', 'Ellis', 'Arlington', 'Renegades', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Isaac', 'Nauta', 'Arlington', 'Renegades', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Taylor', 'Russolino', 'Arlington', 'Renegades', 'K', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Dexter', 'Williams', 'Arlington', 'Renegades', 'RB', 0, 0, 0)

--Houston Roughnecks
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kaleb', 'Eleby', 'Houston', 'Roughnecks', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Cole', 'McDonald', 'Houston', 'Roughnecks', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brandon', 'Silvers', 'Houston', 'Roughnecks', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Trevor', 'Allen', 'Houston', 'Roughnecks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brycen', 'Alleyne', 'Houston', 'Roughnecks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Max', 'Borghi', 'Houston', 'Roughnecks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Adrian', 'Killins', 'Houston', 'Roughnecks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Dejoun', 'Lee', 'Houston', 'Roughnecks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Sewo', 'Olonilua', 'Houston', 'Roughnecks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Chris', 'Booker', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Deontay', 'Burnett', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Cedric', 'Byrd', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('B.J.', 'Byrd', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Travell', 'Harris', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jake', 'Herslow', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jontre', 'Kirklin', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brandon', 'Lewis', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Aaron', 'Nelson', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Antonio', 'NunnW', 'Houston', 'Roughnecks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Antonio', 'Nunn', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ben', 'Putman', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Darece', 'Roberson', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Justin', 'Smith', 'Houston', 'Roughnecks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kyle', 'Fourtenbary', 'Houston', 'Roughnecks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Garrett', 'Owens', 'Houston', 'Roughnecks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('James', 'Stanley', 'Houston', 'Roughnecks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kurt', 'Benkert', 'Houston', 'Roughnecks', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Hunter', 'Duplessis', 'Houston', 'Roughnecks', 'K', 0, 0, 0)

--DC Defenders
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Eric', 'Dungey', 'DC', 'Defenders', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('D’Eriq', 'King', 'DC', 'Defenders', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ryquell', 'Armstead', 'DC', 'Defenders', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brian', 'Herrien', 'DC', 'Defenders', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Artavis', 'Pierce', 'DC', 'Defenders', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Shane', 'Simpson', 'DC', 'Defenders', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Abram', 'Smith', 'DC', 'Defenders', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Pooka', 'Williams', 'DC', 'Defenders', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Manasseh', 'Bailey', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Tariq', 'Bitson', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('K.D.', 'Cannon', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Simmie', 'Cobbs', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jequez', 'Ezzard', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jazz', 'Ferguson', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Josh', 'Hammond', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Lucky', 'Jackson', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Josh', 'Lanier', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Zimari', 'Manning', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Trae', 'Barry', 'DC', 'Defenders', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Bernard', 'McCall', 'DC', 'Defenders', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Tommy', 'McIntyre', 'DC', 'Defenders', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Briley', 'Moore-McKinney', 'DC', 'Defenders', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kahale', 'Warring', 'DC', 'Defenders', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ethan', 'Wolf', 'DC', 'Defenders', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ardarius', 'Stewart', 'DC', 'Defenders', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ardarius', 'Stewart', 'DC', 'Defenders', 'K', 0, 0, 0)

--Orlando Guardians
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Quinten', 'Dormady', 'Orlando', 'Guardians', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Deondre', 'Francois', 'Orlando', 'Guardians', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Mitch', 'Kidd', 'Orlando', 'Guardians', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Darius', 'Clark', 'Orlando', 'Guardians', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Devin', 'Darrington', 'Orlando', 'Guardians', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jah-Maine', 'Martin', 'Orlando', 'Guardians', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kelvin', 'Taylor', 'Orlando', 'Guardians', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Dieuly', 'Aristilde', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Aaron', 'Dilworth', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Dontez', 'Byrd', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Stephen', 'Guidry', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Andrew', 'Jamiel', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Cody', 'Latimer', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Octayvius', 'Miles', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Charleston', 'Rambo', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Eli', 'Rogers', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Patrick', 'Smith', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Bruce', 'Thompson', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Deddrick', 'Thomas', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Bobo', 'Wilson', 'Orlando', 'Guardians', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Tommy', 'Auger', 'Orlando', 'Guardians', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ryan', 'Becker', 'Orlando', 'Guardians', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Logan', 'Carter', 'Orlando', 'Guardians', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Vincent', 'Hobbs', 'Orlando', 'Guardians', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('D’Anfernee', 'McGriff', 'Orlando', 'Guardians', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Justin', 'Rogers', 'Orlando', 'Guardians', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jose', 'Borregales', 'Orlando', 'Guardians', 'K', 0, 0, 0)

--San Antonio Brahmas
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jack', 'Coan', 'San Antonio', 'Brahmas', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jawon', 'Pass', 'San Antonio', 'Brahmas', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Anthony', 'Russo', 'San Antonio', 'Brahmas', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Reid', 'Sinnett', 'San Antonio', 'Brahmas', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kalen', 'Ballage', 'San Antonio', 'Brahmas', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jon', 'Hilliman', 'San Antonio', 'Brahmas', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Moe', 'Neal', 'San Antonio', 'Brahmas', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jacques', 'Patrick', 'San Antonio', 'Brahmas', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Calvin', 'Turner', 'San Antonio', 'Brahmas', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Landen', 'Akers', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Dai’Jean', 'Dixon', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Tabari', 'Hines', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Travis', 'Jonsen', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Camron', 'Lewis', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kendrick', 'Rogers', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Devin', 'Ross', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('T.J.', 'Simmons', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jalen', 'Tolliver', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('TJ', 'Vasher', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Terry', 'Wright', 'San Antonio', 'Brahmas', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Deandre', 'Goolsby', 'San Antonio', 'Brahmas', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Trayvon', 'Hards', 'San Antonio', 'Brahmas', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Alize', 'Mack', 'San Antonio', 'Brahmas', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Marcus', 'Santos-Silva', 'San Antonio', 'Brahmas', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Deon', 'Yelder', 'San Antonio', 'Brahmas', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Denzel', 'Chukwukelu', 'San Antonio', 'Brahmas', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Reggie', 'Corbin', 'San Antonio', 'Brahmas', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Dylan', 'Parham', 'San Antonio', 'Brahmas', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('John', 'Parker', 'San Antonio', 'Brahmas', 'K', 0, 0, 0)

--Seattle Sea Dragons
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ben', 'DiNucci', 'Seattle', 'Sea Dragons', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brian', 'Lewerke', 'Seattle', 'Sea Dragons', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ladarius', 'Galloway', 'Seattle', 'Sea Dragons', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Morgan', 'Ellison', 'Seattle', 'Sea Dragons', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('T.J.', 'Hammonds', 'Seattle', 'Sea Dragons', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brenden', 'Knox', 'Seattle', 'Sea Dragons', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Scottie', 'Phillips', 'Seattle', 'Sea Dragons', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Tayvian', 'Cunningham', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Imoni', 'Donadelle', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Juwan', 'Green', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Josh', 'Gordon', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Blake', 'Jackson', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('McLane', 'Mannix', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kelvin', 'Mcknight', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jahcour', 'Pearson', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jaylon', 'Redd', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kevin', 'Shaa', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jamar', 'Washington', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Damion', 'Willis', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jordan', 'Veasy', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ben', 'Beise', 'Seattle', 'Sea Dragons', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Josh', 'Perkins', 'Seattle', 'Sea Dragons', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Steven', 'Montez', 'Seattle', 'Sea Dragons', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Rashard', 'Davis', 'Seattle', 'Sea Dragons', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brandon', 'Ruiz', 'Seattle', 'Sea Dragons', 'K', 0, 0, 0)

--ST LOUIS Battlehawks
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('A.J.', 'McCarron', 'St. Louis', 'Battlehawks', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Nick', 'Tiano', 'St. Louis', 'Battlehawks', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ryan', 'Willis', 'St. Louis', 'Battlehawks', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Abdul', 'Adams', 'St. Louis', 'Battlehawks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Darius', 'Bradwell', 'St. Louis', 'Battlehawks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Leddie', 'Brown', 'St. Louis', 'Battlehawks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Mataeo', 'Durant', 'St. Louis', 'Battlehawks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brian', 'Hill', 'St. Louis', 'Battlehawks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Taeyler', 'Porter', 'St. Louis', 'Battlehawks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Kareem', 'Walker', 'St. Louis', 'Battlehawks', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Marcell', 'Ateman', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Hakeem', 'Butler', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('George', 'Campbell', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Donteea', 'Dye', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('A.J.', 'Greene', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Hezekiah', 'Grimsley', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Gary', 'Jennings', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Steven', 'Mitchell', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Nyquan', 'Murray', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Bryce', 'Nunnelly', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Austin', 'Proehl', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Darrius', 'Shepherd', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Connor', 'Wedington', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Caleb', 'Vander', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Larry', 'Dalla', 'St. Louis', 'Battlehawks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jovani', 'Haskins', 'St. Louis', 'Battlehawks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Charlie', 'Taumoepeau', 'St. Louis', 'Battlehawks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jaylen', 'Smith', 'St. Louis', 'Battlehawks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jake', 'Sutherland', 'St. Louis', 'Battlehawks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Cam', 'Sutton', 'St. Louis', 'Battlehawks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jordan', 'Thomas', 'St. Louis', 'Battlehawks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jordan', 'Wilson', 'St. Louis', 'Battlehawks', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Ja’Marcus', 'Bradley', 'St. Louis', 'Battlehawks', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Donald', 'Hageman', 'St. Louis', 'Battlehawks', 'K', 0, 0, 0)

--Vegas Vipers
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jalan', 'McClendon', 'Vegas', 'Vipers', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Luis', 'Perez', 'Vegas', 'Vipers', 'QB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Matt', 'Jones', 'Vegas', 'Vipers', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('John', 'Lovett', 'Vegas', 'Vipers', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Rod', 'Smith', 'Vegas', 'Vipers', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('DeAndre', 'Torrey', 'Vegas', 'Vipers', 'RB', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Jeff', 'Badet', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Saeed', 'Blacknall', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Martavis', 'Bryant', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Devion', 'Clayton', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Cyrus', 'Holder', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Isiah', 'Macklin', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Mathew', 'Sexton', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Cinque', 'Sweeting', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Mustaqeem', 'Williams', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Brandon', 'Dillon', 'Vegas', 'Vipers', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Travis', 'Koontz', 'Vegas', 'Vipers', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Sean', 'Price', 'Vegas', 'Vipers', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Nick', 'Guggemos', 'Vegas', 'Vipers', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Grayson', 'Gunter', 'Vegas', 'Vipers', 'TE', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Connor', 'Wedington', 'Vegas', 'Vipers', 'WR', 0, 0, 0)
INSERT INTO PLAYER (first_name, last_name, team_city, team_name, position, total_points, team_id, starting) VALUES ('Bailey', 'Giffen', 'Vegas', 'Vipers', 'K', 0, 0, 0)